"""Add split percentage to UserGroup table

Revision ID: 55028eca7b5c
Revises: 6b9df60eb339
Create Date: 2026-10-07 11:02:27.852625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55028eca7b5c'
down_revision = '6b9df60eb339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_groups', sa.Column('split_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_groups', 'split_percentage')
    # ### end Alembic commands ###
