"""extend users table

Revision ID: 6b9df60eb339
Revises: 0d8b78f76546
Create Date: 2026-10-07 10:52:58.319689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9df60eb339'
down_revision = '0d8b78f76546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('notify_group_invite', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('notify_new_expense', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('notify_settlement', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('notify_removed_from_group', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('pending_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_email')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'notify_removed_from_group')
    op.drop_column('users', 'notify_settlement')
    op.drop_column('users', 'notify_new_expense')
    op.drop_column('users', 'notify_group_invite')
    op.drop_column('users', 'photo_url')
    # ### end Alembic commands ###
