"""Added name column to user table

Revision ID: 91acb19563fb
Revises: 33f0a4e926d7
Create Date: 2026-10-07 15:50:42.968749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91acb19563fb'
down_revision = '33f0a4e926d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
